import os

LORENTZ = 'lorentz'
POINCARE = 'poincare'
EUCLID = 'euclid'
POLITIFACT = 'politifact'
ANTIVAX= 'antivax'
GOSSIPCOP = 'gossipcop'
FIGLANG_TWITTER = 'figlang_twitter'
FIGLANG_REDDIT = 'figlang_reddit'
RUMOUREVAL = 'rumoureval'
TWITTER15 = 'twitter15'
TWITTER16 = 'twitter16'
PHEME = 'pheme'
HYPHEN='hyphen'
HS4='hs4'
BERT='bert'
HAN='han'
DATA_PATH=f'{os.getcwd()}/data'
ROOT_PATH=f'{os.getcwd()}'